# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-18 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possession',
            old_name='card_id',
            new_name='card_name',
        ),
    ]
