# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0002_auto_20170518_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkStatus',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ygoDB.CardStatus')),
                ('link', models.IntegerField(verbose_name='link')),
                ('link_marker', models.CharField(max_length=100, verbose_name='link_marker')),
            ],
            options={
                'db_table': 'link_status',
            },
        ),
        migrations.CreateModel(
            name='PendulumStatus',
            fields=[
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ygoDB.CardStatus')),
                ('pendulum_scale', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13)], verbose_name='pendulum_scale')),
                ('pendulum_effect', models.CharField(max_length=255, verbose_name='pendulum_effect')),
            ],
            options={
                'db_table': 'pendulum_status',
            },
        ),
        migrations.AlterField(
            model_name='cardstatus',
            name='lv',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13)], null=True, verbose_name='lv'),
        ),
    ]
