# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0003_auto_20170522_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardid',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id', to='ygoDB.CardStatus'),
        ),
        migrations.AlterField(
            model_name='linkstatus',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Link', serialize=False, to='ygoDB.CardStatus'),
        ),
        migrations.AlterField(
            model_name='pendulumstatus',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Pendulum', serialize=False, to='ygoDB.CardStatus'),
        ),
        migrations.AlterField(
            model_name='pendulumstatus',
            name='pendulum_effect',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='pendulum_effect'),
        ),
    ]
