# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 07:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0004_auto_20170522_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkMarker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marker', models.IntegerField(verbose_name='marker')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marker', to='ygoDB.CardStatus')),
            ],
        ),
        migrations.RemoveField(
            model_name='linkstatus',
            name='link_marker',
        ),
        migrations.AddField(
            model_name='linkstatus',
            name='link_marker',
            field=models.ManyToManyField(related_name='Link', to='ygoDB.LinkMarker'),
        ),
    ]
