# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 08:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0011_auto_20170522_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmarker',
            name='name',
        ),
    ]
