# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-22 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0012_remove_linkmarker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkmarker',
            name='id',
        ),
        migrations.AlterField(
            model_name='linkmarker',
            name='marker',
            field=models.IntegerField(choices=[(1, '上'), (2, '右上'), (4, '中央'), (6, '左下'), (7, '下'), (8, '右下'), (0, '左上'), (3, '左'), (5, '右')], primary_key=True, serialize=False, verbose_name='marker'),
        ),
    ]
