# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-27 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0014_auto_20170524_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeList',
            fields=[
                ('type', models.CharField(choices=[('通常', '通常'), ('効果', '効果'), ('特殊召喚', '特殊召喚'), ('リバース', 'リバース'), ('ユニオン', 'ユニオン'), ('スピリット', 'スピリット'), ('トゥーン', 'トゥーン'), ('デュアル', 'デュアル'), ('儀式', '儀式'), ('P', 'P'), ('融合', '融合'), ('S', 'S'), ('X', 'X'), ('L', 'L'), ('通常魔法', '通常魔法'), ('装備魔法', '装備魔法'), ('永続魔法', '永続魔法'), ('速攻魔法', '速攻魔法'), ('儀式魔法', '儀式魔法'), ('フィールド魔法', 'フィールド魔法'), ('通常罠', '通常罠'), ('永続罠', '永続罠'), ('カウンター罠', 'カウンター罠')], max_length=20, primary_key=True, serialize=False, verbose_name='type')),
            ],
            options={
                'db_table': 'type_list',
            },
        ),
        migrations.RemoveField(
            model_name='cardstatus',
            name='type',
        ),
        migrations.AlterModelTable(
            name='linkmarker',
            table='link_marker',
        ),
        migrations.AlterModelTable(
            name='packlist',
            table='pack_list',
        ),
        migrations.AddField(
            model_name='cardstatus',
            name='type',
            field=models.ManyToManyField(related_name='status', to='ygoDB.TypeList'),
        ),
    ]
