# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-27 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ygoDB', '0015_auto_20170528_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardid',
            name='recording_pack',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id', to='ygoDB.PackList'),
        ),
        migrations.AlterField(
            model_name='typelist',
            name='type',
            field=models.CharField(choices=[('通常', '通常'), ('効果', '効果'), ('特殊召喚', '特殊召喚'), ('リバース', 'リバース'), ('ユニオン', 'ユニオン'), ('スピリット', 'スピリット'), ('トゥーン', 'トゥーン'), ('デュアル', 'デュアル'), ('儀式', '儀式'), ('P', 'P'), ('融合', '融合'), ('S', 'S'), ('X', 'X'), ('L', 'L'), ('通常魔法', '通常魔法'), ('装備魔法', '装備魔法'), ('永続魔法', '永続魔法'), ('速攻魔法', '速攻魔法'), ('儀式魔法', '儀式魔法'), ('フィールド魔法', 'フィールド魔法'), ('通常罠', '通常罠'), ('永続罠', '永続罠'), ('カウンター罠', 'カウンター罠')], max_length=40, primary_key=True, serialize=False, verbose_name='type'),
        ),
    ]
